DROP SEQUENCE IF exists SEQ_EG_WS_CONN;
DROP SEQUENCE IF exists SEQ_EG_SW_CONN;
DROP SEQUENCE IF exists SEQ_EG_WS_APL;
DROP SEQUENCE IF exists SEQ_EG_SW_APL;

CREATE SEQUENCE SEQ_EG_WS_CONN;
CREATE SEQUENCE SEQ_EG_SW_CONN;
CREATE SEQUENCE SEQ_EG_WS_APL;
CREATE SEQUENCE SEQ_EG_SW_APL;